### ISSUE TITLE
New functionality for using the Azure Create Deployment API.

### ISSUE THREAD

**Issue by rreyes** [chef/knife-azure#176]
I have a need to upload a new service package using the Azure Create Deployment API. Is there a way to do this currently? If not should I implement the functionality?

i.e. http://msdn.microsoft.com/en-us/library/ee460813.aspx

**Comment by Vasu1105** [comment]
@btm your inputs required here.

**Comment by btm** [comment]
I'm not familiar enough with the Azure terminology here, but it sounds like we use [create virtual machine deployment](https://msdn.microsoft.com/en-us/library/jj157194.aspx) which creates a deployment and then a virtual machine inside it of, whereas the requested functionality would just create a deployment. Is it possible to create a virtual machine and add it to an existing deployment? It looks like [create virtual machine deployment](https://msdn.microsoft.com/en-us/library/jj157194.aspx) requires the name of a new unique deployment.

Generally the rule is we only add functionality to knife plugins that we can add value to with Chef, otherwise we don't duplicate functionality from the cloud's own tools, so that we're maintaining and adding matching features all the time.
