### ISSUE TITLE
knife azure server delete doesn't delete servers joined to a domain

### ISSUE THREAD

**Issue by vinyar** [chef/knife-azure#258]
Bug: Nodes which have been created and joined domain do not get delete from Chef Server with `knife azure delete  --purge -y` command.

I would speculate that's because the `node name` become FQDN when joined to a domain: 
Example: `azureServer401` will become `azureServer401.microsoft.com`

/cc: @msnahill for more info

**Comment by siddheshwar-more** [comment]
@vinyar @adamedx 

This is not because of `knife-azure`. Node name is set during bootstrap process by chef-client with the help of `ohai` and windows `ohai` plugin by default takes ruby [`Socket.gethostbyname`] (https://github.com/chef/ohai/blob/f1e35bf1d2352bcec0d8b244fdb575ea031a1ee4/lib/ohai/plugins/hostname.rb#L147-L167) help to set node_name attribute. 

Possible solutions -
 
1. Make --node-name mandatory with --purge option for knife-azure server delete
2. Use solr search query to find out node obj with name like "azureServer401.***"
and delete the node obj.

**Note:**  This will delete all nodes which matches filter.
3.  If knife azure server create is with domian join then we can set `--node-name` to `server name`  programmatically i.e as part of knife azure server create command. 

Please share your views on above approaches.

**Comment by btm** [comment]
Is there any data that comes back from the azure API besides name that would be unique? Any sort of GUID or other unique ID that we might be able to get from the node data via search?

**Comment by Vasu1105** [comment]
@btm we need to find out this.

**Comment by dheerajd-msys** [comment]
1. When we provision VM with `--node-name` option along with `--azure-vm-name` then node gets registered with the provided node name.
So while purging it is necessary to provide `--node-name` to delete the node/client from server else it tries to locate node with `--azure-vm-name` and doesn't find.

2. If we provide only `--azure-vm-name` and create the server then node gets registered with the vm name itself and deletes the node/client with `--purge` option.

**Comment by NimishaS** [comment]
It doesn't seem possible to find the `--node-name` based on `--azure-vm-name`. We are currently showing warning in case the node is not found: https://github.com/chef/knife-azure/pull/418
Closing this issue.
