### ISSUE TITLE
knife azure server create does not respect --secret-file argument for non-Windows hosts

### ISSUE THREAD

**Issue by rubeon** [chef/knife-azure#313]
### Issue
using `--secret-file /path/to/secret_file` command-line argument does not properly transfer the secret file to servers.

Knife bootstrap via other modes works as expected.

### Workaround 
Setting `knife[:secret_file]` in knife.rb works as expected with knife azure plugin.

It might be this:

`./lib/chef/knife/azure_server_create.rb:733:734`

```ruby
      def bootstrap_for_windows_node(server, fqdn, port)
    // snip
        bootstrap.config[:encrypted_data_bag_secret] = locate_config_value(:encrypted_data_bag_secret)
        bootstrap.config[:encrypted_data_bag_secret_file] = locate_config_value(:encrypted_data_bag_secret_file)
```
vs.

`./lib/chef/knife/azure_server_create.rb:753:754`

```ruby

      def bootstrap_for_node(server,fqdn,port)
    // snip

        bootstrap.config[:secret] = locate_config_value(:secret)
        bootstrap.config[:secret_file] = locate_config_value(:secret_file)
```

Thanks,
Eric

**Comment by dheerajd-msys** [comment]
Hi @rubeon,

Thanks for the information.
When using --secret-file option, the value is assigned to `config[:encrypted_data_bag_secret_file]`. 
Even after assigning value to `config[:secret_file]`  from `config[:encrypted_data_bag_secret_file]`, it wasn't working.
The reason is as follows:-
The long value --secret-file option points to 2 different parameters(one parameter for windows and one for linux)
1. In `knife-windows-1.3.0/lib/chef/knife/bootstrap_windows_base.rb` file, we have the `encrypted_data_bag_secret` parameter.
2. In `chef-12.8.1/lib/chef/knife/data_bag_secret_options.rb` file, we have `secret_file` parameter.

Because of `include Knife::BootstrapWindowsBase` at `lib/chef/knife/azure_server_create.rb:32`, windows optional parameters are imported, but not chef's optional parameters.

chef's optional parameter(secret_file) have a proc function which sets the value passed to Chef::Config[:knife][:cl_secret_file], hence passing the secret file to config parameter in bootstrap doesn't work as the Linux bootstrap method internally checks if Chef::Config[:knife][:cl_secret_file] is present or not, so setting it to `Chef::Config[:knife][:secret_file]` resolves the issue.

So, after setting the `--secret-file` value passed  to `Chef::Config[:knife][:secret_file]` in `./lib/chef/knife/azure_server_create.rb` file, it works properly and the secret file does gets copied to `/etc/chef/encrypted_data_bag_secret` on the spawned vm.

Also i found similar issue occurs for --secret option also, i have fixed that issue also.

**Comment by NimishaS** [comment]
@rubeon, the fix has been merged in `master` branch. Please verify.

**Comment by Vasu1105** [comment]
@rubeon Could you please check at your end with latest changes so that we can close this issue.

**Comment by rubeon** [comment]
Hi,  I'm not using the plugin any more, so don't wait for me.  If it comes up in the future, I will raise the issue again.

Thanks,
Eric
